-- Create schema for tests
CREATE SCHEMA IF NOT EXISTS pet_schema;

-- Grant privileges
GRANT ALL PRIVILEGES ON SCHEMA pet_schema TO test;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA pet_schema TO test;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA pet_schema TO test;
ALTER DEFAULT PRIVILEGES IN SCHEMA pet_schema GRANT ALL ON TABLES TO test;
ALTER DEFAULT PRIVILEGES IN SCHEMA pet_schema GRANT ALL ON SEQUENCES TO test;

